baseurl = "https://qri.io/"
relativeURLs = true
# builddrafts = false
# canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "qri.io"
title = "qri"
pluralizelisttitles = false
theme="kube"

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
# [[menu.main]]
#     name = "Blog"
#     weight = -100
#     url = "/blog/"
# [[menu.main]]
#     name = "Faq"
#     weight = -100
#     url = "/faq/"

[permalinks]
blog = ":slug/"

[params]
IsDev = false
Author = "qri"
# CacheBuster = true
DateForm = "Jan 2, 2006"
DateFormFull = "Mon Jan 2 2006 15:04:05 MST"
Description = "a home for datasets"
Email = "info@qri.io"
FaviconFile = "img/leaf.ico"
SegmentTracker= "b4iAxJT8ISitRFQ6qZGS9w7RTnaOpvju"
GitHub = "qri-io"
# Lang = "en"
# LinkedIn = "//linkedin.com/in/you"
Twitter = "qri_io"
