baseurl = "https://qri.io/"
relativeURLs = true
languageCode = "en-us"
title = "qri"
author = "qri.io"
theme="qri"
pluralizelisttitles = false

[[menu.main]]
    name = "Docs"
    weight = -100
    url = "/docs/"
[[menu.main]]
    name = "Download"
    weight = -100
    url = "/download/"

# [[menu.main]]
#     name = "Faq"
#     weight = -100
#     url = "/faq/"
# [permalinks]
#   blog = ":slug/"

[[menu.docs]]
    name = "Download"
    weight = -100
    url = "/download/"

[params]
IsDev = false
Author = "qri"
# CacheBuster = true
DateForm = "Jan 2, 2006"
DateFormFull = "Mon Jan 2 2006 15:04:05 MST"
Description = "a home for datasets"
Email = "info@qri.io"
FaviconFile = "img/leaf.ico"
SegmentTracker= "b4iAxJT8ISitRFQ6qZGS9w7RTnaOpvju"
GitHub = "qri-io"
# Lang = "en" 
# LinkedIn = "//linkedin.com/in/you"
Twitter = "qri_io"
