
name = "qri_io"
license = "MIT"
licenselink = "https://github.com/qri-io/website/master/LICENSE.md"
description = "qri is the qri.io theme for hugo"
homepage = "https://qri.io"
tags = ["web", "site"]
features = ["it's a web site", "you can read it", "mad dope"]
min_version = 0.19

[author]
  name = "b5"
  homepage = "https://brendan.nyc"
